// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class AccountEntity
{
    /// <summary>
    /// L&apos;identifiant technique
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// L&apos;identifiant global de l&apos;entité
    /// </summary>
    public Guid AccountGlobalUniqueId { get; set; }

    public string AccountNumber { get; set; }

    /// <summary>
    /// La raison social de l&apos;entité
    /// </summary>
    public string LegalName { get; set; }

    /// <summary>
    /// Le  nom commercial de l&apos;entité
    /// </summary>
    public string CommercialName { get; set; }

    /// <summary>
    /// Le type de l&apos;entité
    /// </summary>
    public string AccountType { get; set; }

    /// <summary>
    /// L&apos;adresse mail de l&apos;entité
    /// </summary>
    public string Email { get; set; }

    public string DeliveryEmail { get; set; }

    public string BillingEmail { get; set; }

    public string DeliveryFax { get; set; }

    public string BillingFax { get; set; }

    /// <summary>
    /// L&apos;identifiant technique du Hub
    /// </summary>
    public int? HubId { get; set; }

    /// <summary>
    /// L&apos;identifiant technique du code Naf
    /// </summary>
    public int? NafId { get; set; }

    /// <summary>
    /// L&apos;entité est-elle activé
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// Le code du secteur
    /// </summary>
    public string SectorCode { get; set; }

    /// <summary>
    /// Le secteur
    /// </summary>
    public string Sector { get; set; }

    /// <summary>
    /// La plage du nombre de salariés 
    /// </summary>
    public string StaffSizeRange { get; set; }

    /// <summary>
    /// Le type de comptabilité
    /// </summary>
    public string AccountingMethod { get; set; }

    /// <summary>
    /// Le chiffre d&apos;affaires
    /// </summary>
    public decimal? Turnover { get; set; }

    /// <summary>
    /// Le code de la forme juridique
    /// </summary>
    public string LegalFormCode { get; set; }

    /// <summary>
    /// La forme juridique de l&apos;entité
    /// </summary>
    public string LegalForm { get; set; }

    /// <summary>
    /// Le régime fiscale
    /// </summary>
    public string FiscalSystem { get; set; }

    /// <summary>
    /// Début Exercice fiscale
    /// </summary>
    public DateTime? FiscalExerciseStartDate { get; set; }

    /// <summary>
    /// La durée de l&apos;exercice fiscale
    /// </summary>
    public int? FiscalExerciseDuration { get; set; }

    /// <summary>
    /// Le ISIN
    /// </summary>
    public string Isin { get; set; }

    /// <summary>
    /// Le Siret
    /// </summary>
    public string Siret { get; set; }

    /// <summary>
    /// Le Régime d&apos;imposition
    /// </summary>
    public string TaxationSystem { get; set; }

    /// <summary>
    /// Description de l&apos;activité
    /// </summary>
    public string ActivityDescription { get; set; }

    /// <summary>
    /// Type d&apos;activité
    /// </summary>
    public string ActivityType { get; set; }

    /// <summary>
    /// La TVA
    /// </summary>
    public string Vat { get; set; }

    /// <summary>
    /// Le numéro de TVA intracommunautaire
    /// </summary>
    public string Vatintra { get; set; }

    /// <summary>
    /// Type de TVA
    /// </summary>
    public string Vattype { get; set; }

    /// <summary>
    /// Le nombre d&apos;employés de l&apos;entité
    /// </summary>
    public int? StaffSize { get; set; }

    public string SourceName { get; set; }

    /// <summary>
    /// L&apos;identifiant de l&apos;utilisateur ou du système qui a crée l&apos;entité
    /// </summary>
    public string CreatedBy { get; set; }

    /// <summary>
    /// L&apos;identifiant de l&apos;utilisateur ou du système qui a effectué la dernière modification
    /// </summary>
    public string ModifiedBy { get; set; }

    /// <summary>
    /// La date de création
    /// </summary>
    public DateTime CreationDate { get; set; }

    /// <summary>
    /// La date de la dernière modification
    /// </summary>
    public DateTime? UpdatedDate { get; set; }

    public string IconName { get; set; }

    public string MissionType { get; set; }

    public int? OfficeId { get; set; }

    public virtual ICollection<AddressEntity> AddressEntity { get; set; } = new List<AddressEntity>();

    public virtual ICollection<DelegationRequestEntity> DelegationRequestEntity { get; set; } = new List<DelegationRequestEntity>();

    public virtual DeploymentEntity DeploymentEntity { get; set; }

    public virtual HubEntity Hub { get; set; }

    public virtual NafEntity Naf { get; set; }

    public virtual OfferEligibilityEntity OfferEligibilityEntity { get; set; }

    public virtual OfficeEntity Office { get; set; }

    public virtual ICollection<PhoneEntity> PhoneEntity { get; set; } = new List<PhoneEntity>();

    public virtual ICollection<RoleEntity> RoleEntity { get; set; } = new List<RoleEntity>();

     public virtual ICollection<RoleLabelEntity> RoleLabelEntity { get; set; } = new List<RoleLabelEntity>();

     public virtual ICollection<DelegationEntity> Delegation { get; set; } = new List<DelegationEntity>();

     public virtual ICollection<InvoiceEntity> InvoiceEntity { get; set; } = new List<InvoiceEntity>();
}