// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class AddressEntity
{
    /// <summary>
    /// L&apos;&apos;identifiant technique
    /// </summary>
    public int AddressId { get; set; }

    /// <summary>
    /// L&apos;&apos;identifiant de l&apos;&apos;entité
    /// </summary>
    public int? AccountId { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    /// <summary>
    /// Le code postal
    /// </summary>
    public string ZipCode { get; set; }

    /// <summary>
    /// La ville
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// Le département
    /// </summary>
    public string State { get; set; }

    /// <summary>
    /// Le pays
    /// </summary>
    public string Country { get; set; }

    public decimal Latitude { get; set; } = default!;

    public decimal Longitude { get; set; } = default!;

    /// <summary>
    /// Le type d&apos;&apos;adresse
    /// </summary>
    public string AddressType { get; set; }

    public virtual AccountEntity? Account { get; set; }

    public virtual ICollection<OfficeEntity>? OfficeEntities { get; set; } = [];
}
