// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class DelegationRequestEntity
{
    /// <summary>
    /// L&apos;identifiant technique de la demande de délégation
    /// </summary>
    public int DelegationRequestId { get; set; }

    /// <summary>
    /// L&apos;identifiant du contact demandeur
    /// </summary>
    public int RequesterId { get; set; }

    /// <summary>
    /// L&apos;identifiant du contact destinataire
    /// </summary>
    public int RecipientId { get; set; }

    /// <summary>
    /// L&apos;identifiant du dossier concerné par la demande
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// La date de création de la demande
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Le statut de la demande (pending, accepted, refused)
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// La date de réponse à la demande (acceptation ou refus)
    /// </summary>
    public DateTime? RespondedAt { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual ContactEntity Recipient { get; set; }

    public virtual ContactEntity Requester { get; set; }
}