// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class DelegationEntity
{
    /// <summary>
    /// L&apos;&apos;identifiant technique
    /// </summary>
    public int DelegationId { get; set; }

    /// <summary>
    /// Le délégateur 
    /// </summary>
    public int DelegatorId { get; set; }

    /// <summary>
    /// L&apos;&apos;identifiant du délégataire
    /// </summary>
    public int DelegateeId { get; set; }

    /// <summary>
    /// La date effective du début de la délégation
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// La date effective de la fin de la délégation
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// La délégation est-elle active ou non
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// La note associé à la délégation
    /// </summary>
    public string Note { get; set; }

    /// <summary>
    /// La date de création de la délégation
    /// </summary>
    public DateTime CreationDate { get; set; }

    /// <summary>
    /// Indique si la délégation concerne l&apos;&apos;intégralité du portefeuille ou non
    /// </summary>
    public bool IsFullDelegation { get; set; }

    /// <summary>
    /// Indique s&apos;&apos;il s&apos;&apos;agit d&apos;&apos;une délégation automatique
    /// </summary>
    public bool IsAutomaticDelegation { get; set; }

    public virtual ContactEntity Delegatee { get; set; }

    public virtual ContactEntity Delegator { get; set; }

    public virtual ICollection<AccountEntity> Account { get; set; } = new List<AccountEntity>();
}