// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class DematModalClosureEntity
{
    /// <summary>
    /// L&apos;identifiant technique du compte, clé primaire composite avec ContactId (une fermeture par contact et par compte)
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// L&apos;identifiant du contact ayant fermé le modal, clé primaire composite avec AccountId (chaque contact ferme son propre modal, indépendamment des autres contacts du compte)
    /// </summary>
    public int ContactId { get; set; }

    /// <summary>
    /// La date de fermeture du modal
    /// </summary>
    public DateTime ClosedDate { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual ContactEntity Contact { get; set; }
}
