// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class InvoiceEntity
{
    /// <summary>
    /// L&apos;identifiant technique
    /// </summary>
    public int InvoiceId { get; set; }

    /// <summary>
    /// Le numéro de facture (identifiant externe unique)
    /// </summary>
    public string InvoiceNumber { get; set; }

    /// <summary>
    /// Le chemin du document (nom affiché = dernier segment)
    /// </summary>
    public string DocumentPath { get; set; }

    /// <summary>
    /// Le type de facture (ex: Facture RYDGE)
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// La catégorie de facture
    /// </summary>
    public string Category { get; set; }

    /// <summary>
    /// La date de facturation
    /// </summary>
    public DateTime InvoiceDate { get; set; }

    /// <summary>
    /// La date de dépôt
    /// </summary>
    public DateTime DepositDate { get; set; }

    /// <summary>
    /// L&apos;identifiant technique de l&apos;entité
    /// </summary>
    public int AccountId { get; set; }

    public virtual AccountEntity Account { get; set; }
}