// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class LabelEntity
{
    public int LabelId { get; set; }

    public string Code { get; set; }

    public string CustomerLabel { get; set; }

    public string CollaboratorLabel { get; set; }

    public string Description { get; set; }

    public string Business { get; set; }

    public bool IsVisible { get; set; }

    public virtual ICollection<RoleLabelEntity> RoleLabelEntity { get; set; } = new List<RoleLabelEntity>();
}