// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class NafEntity
{
    /// <summary>
    /// L&apos;&apos;identifiant technique
    /// </summary>
    public int NafId { get; set; }

    /// <summary>
    /// Le code Naf de l&apos;&apos;entité
    /// </summary>
    public string NafCode { get; set; }

    public string NafLabel { get; set; }

    public virtual ICollection<AccountEntity> AccountEntity { get; set; } = new List<AccountEntity>();
}