// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class OfferEligibilityEntity
{
    /// <summary>
    /// Identifiant technique du compte (clé primaire et étrangère vers account.Account)
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// Nom de l&apos;offre associée à ce compte
    /// </summary>
    public string OfferName { get; set; }

    /// <summary>
    /// Indique si le compte est éligible à l&apos;offre (1 = Oui, 0 = Non)
    /// </summary>
    public bool IsEligible { get; set; }

    /// <summary>
    /// Date de validation de l&apos;offre
    /// </summary>
    public DateTime? ApprovedDate { get; set; }

    /// <summary>
    /// Utilisateur ou processus ayant validé l&apos;offre
    /// </summary>
    public string ApprovedBy { get; set; }

    public int? ReportId { get; set; }

    public string ReportLabel { get; set; }

    public virtual AccountEntity Account { get; set; }
}