// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class OfficeEntity
{
    public int OfficeId { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public int AddressId { get; set; }

    public virtual ICollection<AccountEntity> AccountEntity { get; set; } = new List<AccountEntity>();

    public virtual AddressEntity Address { get; set; }
}