// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class PhoneEntity
{
    /// <summary>
    /// L&apos;identifiant technique
    /// </summary>
    public int PhoneId { get; set; }

    /// <summary>
    /// L&apos;identifiant techique de l&apos;entité
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// Le numéro de téléphone
    /// </summary>
    public string PhoneNumber { get; set; }

    /// <summary>
    /// Le type du numéro de téléphone
    /// </summary>
    public string Type { get; set; }

    public virtual AccountEntity Account { get; set; }
}