// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class RoleEntity
{
    /// <summary>
    /// L&apos;&apos;identifiant technique de l&apos;&apos;entité
    /// </summary>
    public int AccountId { get; set; }

    /// <summary>
    /// L&apos;&apos;identifiant technique du contact
    /// </summary>
    public int ContactId { get; set; }

    /// <summary>
    /// Le rôle est-il considéré comme un favori ou mis en avant comme tel
    /// </summary>
    public bool? IsFavorite { get; set; }

    /// <summary>
    /// Le signataire
    /// </summary>
    public bool? IsSignatory { get; set; }

    /// <summary>
    /// Indique, dans les cas où c&apos;&apos;est possible, si le role est lié à une délégation
    /// </summary>
    public bool? IsDelegation { get; set; }

    public bool? IsCustomerRelation { get; set; }

    public bool? IsActor { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual ContactEntity Contact { get; set; }
}
