// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class RoleLabelEntity
{
    public int AccountId { get; set; }

    public int ContactId { get; set; }

    public int LabelId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual ContactEntity Contact { get; set; }

    public virtual ContactEntity CreatedByNavigation { get; set; }

    public virtual LabelEntity Label { get; set; }
}