// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities;

public partial class SerenityChoiceEntity
{
    /// <summary>
    /// Identifiant technique du contact ayant fait le choix (clé primaire et étrangère vers actor.Contact). La présence de la ligne vaut &quot;un choix a été fait&quot;.
    /// </summary>
    public int ContactId { get; set; }

    /// <summary>
    /// Choix exprimé par le contact sur la modal Sérénité (1 = accepté, 0 = refusé). Conservé pour le métier : la décision d&apos;affichage ne dépend que de l&apos;existence de la ligne.
    /// </summary>
    public bool IsAccepted { get; set; }

    /// <summary>
    /// Date UTC à laquelle le choix a été enregistré
    /// </summary>
    public DateTime ChoiceDate { get; set; }
}
