// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Kpmg.Account.Core.Models;
using AccountModel = Kpmg.Account.Core.Models.Account;

namespace Pulse.Account.Infrastructure.Entities
{
    public partial class TAccount
    {
        public TAccount()
        {
            TAddress = new HashSet<TAddress>();
            TDelegation = new HashSet<TDelegation>();
            TDeploymentPlanning = new HashSet<TDeploymentPlanning>();
            TPhone = new HashSet<TPhone>();
            TRoles = new HashSet<TRoles>();
        }

        /// <summary>
        /// L&apos;identifiant technique
        /// </summary>
        public int AccountId { get; set; }
        /// <summary>
        /// L&apos;identifiant global de l&apos;entité
        /// </summary>
        public Guid AccountGlobalUniqueId { get; set; }
        /// <summary>
        /// La raison social de l&apos;entité
        /// </summary>
        public string LegalName { get; set; }
        /// <summary>
        /// Le  nom commercial de l&apos;entité
        /// </summary>
        public string CommercialName { get; set; }
        /// <summary>
        /// Le type de l&apos;entité
        /// </summary>
        public string AccountType { get; set; }
        /// <summary>
        /// L&apos;adresse mail de l&apos;entité
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// L&apos;identifiant technique du Hub
        /// </summary>
        public int? HubId { get; set; }
        /// <summary>
        /// L&apos;identifiant technique du code Naf
        /// </summary>
        public int NafId { get; set; }
        /// <summary>
        /// L&apos;entité est-elle activé
        /// </summary>
        public bool IsActive { get; set; }
        /// <summary>
        /// La source de création de l&apos;entité
        /// </summary>
        public string SourceAccountNumber { get; set; }
        /// <summary>
        /// Le code du secteur
        /// </summary>
        public string SectorCode { get; set; }
        /// <summary>
        /// Le secteur
        /// </summary>
        public string Sector { get; set; }
        /// <summary>
        /// La plage du nombre de salariés 
        /// </summary>
        public string StaffSizeRange { get; set; }
        /// <summary>
        /// Le type de comptabilité
        /// </summary>
        public string AccountingMethod { get; set; }
        /// <summary>
        /// Le chiffre d&apos;affaires
        /// </summary>
        public decimal? Turnover { get; set; }
        /// <summary>
        /// Le code de la forme juridique
        /// </summary>
        public string LegalFormCode { get; set; }
        /// <summary>
        /// La forme juridique de l&apos;entité
        /// </summary>
        public string LegalForm { get; set; }
        /// <summary>
        /// Le régime fiscale
        /// </summary>
        public string FiscalSystem { get; set; }
        /// <summary>
        /// Début Exercice fiscale
        /// </summary>
        public DateTime? FiscalExerciseStartDate { get; set; }
        /// <summary>
        /// La durée de l&apos;exercice fiscale
        /// </summary>
        public int? FiscalExerciseDuration { get; set; }
        /// <summary>
        /// Le ISIN
        /// </summary>
        public string ISIN { get; set; }
        /// <summary>
        /// Le Siret
        /// </summary>
        public string Siret { get; set; }
        /// <summary>
        /// Le Régime d&apos;imposition
        /// </summary>
        public string TaxationSystem { get; set; }
        /// <summary>
        /// Description de l&apos;activité
        /// </summary>
        public string ActivityDescription { get; set; }
        /// <summary>
        /// Type d&apos;activité
        /// </summary>
        public string ActivityType { get; set; }
        /// <summary>
        /// La TVA
        /// </summary>
        public string VAT { get; set; }
        /// <summary>
        /// Le numéro de TVA intracommunautaire
        /// </summary>
        public string VATIntra { get; set; }
        /// <summary>
        /// Type de TVA
        /// </summary>
        public string VATType { get; set; }
        /// <summary>
        /// Le nombre d&apos;employés de l&apos;entité
        /// </summary>
        public int? StaffSize { get; set; }
        /// <summary>
        /// L&apos;identifiant de l&apos;utilisateur ou du système qui a crée l&apos;entité
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// L&apos;identifiant de l&apos;utilisateur ou du système qui a effectué la dernière modification
        /// </summary>
        public string ModifiedBy { get; set; }
        /// <summary>
        /// La date de création
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// La date de la dernière modification
        /// </summary>
        public DateTime? UpdatedDate { get; set; }

        public virtual THub Hub { get; set; }
        public virtual TNaf HubNavigation { get; set; }
        public virtual ICollection<TAddress> TAddress { get; set; }
        public virtual ICollection<TDelegation> TDelegation { get; set; }
        public virtual ICollection<TDeploymentPlanning> TDeploymentPlanning { get; set; }
        public virtual ICollection<TPhone> TPhone { get; set; }
        public virtual ICollection<TRoles> TRoles { get; set; }

        public AccountModel TAccountToAccountModel(int contactId)
        {
            var roleSignatory = this.TRoles.FirstOrDefault(role => role.IsSignatory == true);
            var roleConnectedContact = this.TRoles?.FirstOrDefault(role => role.ContactId == contactId);
            return new AccountModel()
            {
                AccountId = this.AccountGlobalUniqueId,
                AccountNumber = this.SourceAccountNumber,
                LegalName = this.LegalName,
                IsFavorite = roleConnectedContact != null ? roleConnectedContact?.IsFavorite : false,
                Address = this.TAddress?.Select(address => new Address()
                {
                    City = address.City,
                    AddressType = address.AddressType
                }),
                Owner = new Owner()
                {
                    ContactEmail = roleSignatory?.Contact.ContactEmail,
                    FirstName = roleSignatory?.Contact.FirstName,
                    LastName = roleSignatory?.Contact.LastName
                },
                Deployment = this.TDeploymentPlanning?.Select(deploymentPlanning => new Deployment() { Status = deploymentPlanning.Status })
            };
        }

        public AccountDetail TAccountToAccountDetail()
        {
            return new AccountDetail()
            {
                AccountId = this.AccountGlobalUniqueId.ToString(),
                AccountNumber = this.SourceAccountNumber,
                IconName = "icon",
                IsActive = this.IsActive,
                Email = this.Email,
                EmployeeCount = this.StaffSize,
                CommercialName = this.CommercialName,
                Accounting = new Accounting()
                {
                    FiscalExerciseStartDate = this.FiscalExerciseStartDate.ToString(),
                    FiscalExerciseDuration = this.FiscalExerciseDuration,
                    AccountingType = this.AccountType,
                    FiscalSystem = this.FiscalSystem
                },
                Legal = new Legal()
                {
                    LegalName = this.LegalName,
                    Siren = this.ISIN,
                    Siret = this.Siret,
                    LegalForm = this.LegalForm,
                    LegalFormCode = this.LegalFormCode,
                    StaffSizeRange = this.StaffSizeRange,
                    Naf = new List<Naf>() {
                                new Naf()
                                {
                                    NafId = this.NafId,
                                    NafCode = this.SectorCode,
                                    NafLabel = this.ActivityDescription
                                }
                            }
                },
                Vat = new Vat()
                {
                    System = this.VAT,
                    Intra = this.VATIntra,
                    Type = this.VATType,
                },
                Address = this.TAddress.Select(address => new Address()
                {
                    AddressId = address.AddressId,
                    Country = address.Country,
                    City = address.City,
                    State = address.State,
                    Street = address.Street,
                    ZipCode = address.ZipCode,
                    AddressType = address.AddressType
                }).ToList(),
                Phone = this.TPhone.Select(phone => new Phone()
                {
                    PhoneId = phone.PhoneId,
                    PhoneNumber = phone.PhoneNumber,
                    Type = phone.Type,
                }).ToList(),
                Hub = new Hub()
                {
                    HubId = this.Hub?.HubId,
                    HubName = this.Hub?.HubName,
                },
                DeploymentPlanning = this.TDeploymentPlanning.Select(deployment => new Deployment()
                {
                    DeploymentId = deployment.DeploymentId,
                    DeploymentDate = deployment.DeploymentDate.ToString(),
                    Status = deployment.Status,
                }).ToList()
            };
        }
    }
}
