// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities
{
    public partial class TDelegation
    {
        /// <summary>
        /// L&apos;&apos;identifiant technique
        /// </summary>
        public int DelegationId { get; set; }
        /// <summary>
        /// L&apos;&apos;identifiant technique de l&apos;&apos;entité
        /// </summary>
        public int AccountId { get; set; }
        /// <summary>
        /// Le délégateur 
        /// </summary>
        public int DelegatorId { get; set; }
        /// <summary>
        /// Le délégataire
        /// </summary>
        public int DelegateeId { get; set; }
        /// <summary>
        /// La date effective du début de la délégation
        /// </summary>
        public DateTime StartDate { get; set; }
        /// <summary>
        /// La date effective de la fin de la délégation
        /// </summary>
        public DateTime? EndDate { get; set; }
        /// <summary>
        /// La délégation est-elle active ou non
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// La note associé à la délégation
        /// </summary>
        public string Note { get; set; }
        /// <summary>
        /// La date de création de la délégation
        /// </summary>
        public DateTime CreationDate { get; set; }

        public virtual TAccount Account { get; set; }
        public virtual TContact Delegatee { get; set; }
        public virtual TContact Delegator { get; set; }
    }
}
