// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Account.Infrastructure.Entities
{
    public partial class THub
    {
        public THub()
        {
            TAccount = new HashSet<TAccount>();
        }

        /// <summary>
        /// L&apos;&apos;identifiant technique
        /// </summary>
        public int HubId { get; set; }
        /// <summary>
        /// Le nom du Hub
        /// </summary>
        public string HubName { get; set; }

        public virtual ICollection<TAccount> TAccount { get; set; }
    }
}