// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kpmg.Offer.Infrastructure.Entities
{
    public partial class TOffer
    {
        public TOffer()
        {
            TProductConfiguration = new HashSet<TProductConfiguration>();
        }

        /// <summary>
        /// ID technique
        /// </summary>
        public int OfferId { get; set; }
        /// <summary>
        /// Nom de l&apos;offre
        /// </summary>
        public string OfferName { get; set; }
        public string OfferPriceType { get; set; }
        /// <summary>
        /// Libellé de l&apos;offre
        /// </summary>
        public string OfferLabel { get; set; }
        /// <summary>
        /// Description de l&apos;offre
        /// </summary>
        public string OfferDescription { get; set; }
        /// <summary>
        /// ID technique utilisé dans la base Constellation
        /// </summary>
        public Guid? GlobalOfferId { get; set; }
        /// <summary>
        /// Prix de l&apos;offre
        /// </summary>
        public decimal? OfferPrice { get; set; }
        /// <summary>
        /// Lien vers le book des offres
        /// </summary>
        public string OffersBookLink { get; set; }
        /// <summary>
        /// Lien vers le lien intranet
        /// </summary>
        public string IntranetLink { get; set; }
        /// <summary>
        /// Liste de tags
        /// </summary>
        public string Tags { get; set; }
        /// <summary>
        /// Indique si une validation est nécessaire ou non
        /// </summary>
        public bool? ApprovalRequired { get; set; }
        /// <summary>
        /// Logo de l&apos;&apos;offre
        /// </summary>
        public string LogoName { get; set; }

        public virtual ICollection<TProductConfiguration> TProductConfiguration { get; set; }
    }
}
