// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kpmg.Offer.Infrastructure.Entities
{
    public partial class TProvider
    {
        public TProvider()
        {
            TProduct = new HashSet<TProduct>();
        }

        /// <summary>
        /// ID technique
        /// </summary>
        public int ProviderId { get; set; }
        /// <summary>
        /// Nom de la prestation commerciale
        /// </summary>
        public string ProviderName { get; set; }
        /// <summary>
        /// Nom de l&apos;éditeur de la prestation
        /// </summary>
        public string ProviderEditor { get; set; }
        /// <summary>
        /// Pulse, interne KPMG ou externe
        /// </summary>
        public string ProviderCategory { get; set; }
        /// <summary>
        /// Logo du provider
        /// </summary>
        public string LogoName { get; set; }

        public virtual ICollection<TProduct> TProduct { get; set; }
    }
}
