// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kpmg.Offer.Infrastructure.Entities
{
    public partial class TProductConfiguration
    {
        /// <summary>
        /// ID de l&apos;offre associée
        /// </summary>
        public int OfferId { get; set; }
        /// <summary>
        /// ID du service associé
        /// </summary>
        public int ProductId { get; set; }
        /// <summary>
        /// Date
        /// </summary>
        public DateTime? Date { get; set; }
        /// <summary>
        /// Si le service est obligatoire ou optionnel dans l&apos;offre associée
        /// </summary>
        public bool IsOptionnal { get; set; }
        /// <summary>
        /// Prix du service (s&apos;il est optionnel)
        /// </summary>
        public decimal? Price { get; set; }
        /// <summary>
        /// Si le service est activé ou non
        /// </summary>
        public bool Enabled { get; set; }
        /// <summary>
        /// Le type du prix du produit
        /// </summary>
        public string PriceType { get; set; }
        /// <summary>
        /// ID technique
        /// </summary>
        public int ProductConfigurationId { get; set; }
        /// <summary>
        /// ID technique utilisé dans la base Constellation
        /// </summary>
        public Guid? GlobalProductConfigurationId { get; set; }

        public virtual TOffer TOffer { get; set; }
        public virtual TProduct TProduct { get; set; }
    }
}
