// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kpmg.Offer.Infrastructure.Entities
{
    public partial class TProduct
    {
        public TProduct()
        {
            TProductConfiguration = new HashSet<TProductConfiguration>();
        }

        /// <summary>
        /// ID technique
        /// </summary>
        public int ProductId { get; set; }
        /// <summary>
        /// Acteur externe, Pulse, équipe BI...
        /// </summary>
        public int ProviderId { get; set; }
        /// <summary>
        /// Nom du service
        /// </summary>
        public string ProductName { get; set; }
        /// <summary>
        /// Libellé service
        /// </summary>
        public string ProductLabel { get; set; }
        /// <summary>
        /// Description du service
        /// </summary>
        public string ProductDescription { get; set; }
        /// <summary>
        /// Nom public du service
        /// </summary>
        public string PublicProductName { get; set; }
        /// <summary>
        /// Libellé public du service
        /// </summary>
        public string PublicProductLabel { get; set; }
        /// <summary>
        /// Description public du service
        /// </summary>
        public string PublicProductDescription { get; set; }
        /// <summary>
        /// Comptabilité, gestion sociale, juridique, transverse
        /// </summary>
        public string ProductBusiness { get; set; }
        /// <summary>
        /// Indique si le service est disponible ou non
        /// </summary>
        public bool Enabled { get; set; }

        public virtual TProvider TProvider { get; set; }
        public virtual ICollection<TProductConfiguration> TProductConfiguration { get; set; }
    }
}
