<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Pulse.Account.Core</AssemblyName>
		<RootNamespace>Pulse.Account.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Configuration\**" />
	  <EmbeddedResource Remove="Configuration\**" />
	  <None Remove="Configuration\**" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Kpmg.ExceptionMiddleware" Version="1.73.7" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="8.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="System.Text.Json" Version="8.0.0" />
	</ItemGroup>

</Project>
