<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Pulse.Account.Core</AssemblyName>
		<RootNamespace>Pulse.Account.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Configuration\**" />
	  <EmbeddedResource Remove="Configuration\**" />
	  <None Remove="Configuration\**" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="ClosedXML" Version="0.105.0" />
	  <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="8.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="9.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="Pulse.Back.Events" Version="2.74.206" />
	  <PackageReference Include="Pulse.ExceptionMiddleware" Version="2.73.53" />
	  <PackageReference Include="System.Text.Json" Version="9.0.8" />
	</ItemGroup>

</Project>
