DBCC CHECKIDENT ('actor.Contact', RESEED, 0);

INSERT into actor.Contact(ContactId, ContactGlobalUniqueId, FirstName, LastName, Email, Type, Status, CreationDate, PersonaName)
VALUES
(1,NEWID(),'Yasser','Arouaoui','yarouaoui@kpmg.fr','collaborator','declared',GETDATE(),''),
(2,NEWID(),'Wael','Ben Abdellatif','wbenabdelatif@kpmg.fr','collaborator','declared',GETDATE(),''),
(3,NEWID(),'Selim','Ben Slimen','sbenslimen@kpmg.fr','collaborator','declared',GETDATE(),''),
(4,NEWID(),'Ahmed','Yaiche','ahmedyaiche@kpmg.fr','collaborator','declared',GETDATE(),''),
(5,NEWID(),'Oussema','Ben Amor','obenamor@kpmg.fr','collaborator','declared',GETDATE(),''),
(6,NEWID(),'Siwar','Ben Dhafer','sbendhafer@kpmg.fr','collaborator','declared',GETDATE(),''),
(7,NEWID(),'Hervé','Chaissac','hchaissac@kpmg.fr','collaborator','declared',GETDATE(),''),
(8,NEWID(),'Naoual','El Farissi','nelfarissi@kpmg.fr','collaborator','declared',GETDATE(),''),
(9,NEWID(),'Kaoutar','Khamliche','kkhamliche@kpmg.fr','collaborator','declared',GETDATE(),''),
(10,NEWID(),'Erwan','Munier','emunier@kpmg.fr','collaborator','declared',GETDATE(),''),
(11,NEWID(),'Kevin','Pozderec','kpozderec@kpmg.fr','collaborator','declared',GETDATE(),''),
(12,NEWID(),'Rayan','Ramanampamonjy','rramanampamonjy@kpmg.fr','collaborator','declared',GETDATE(),''),
(13,NEWID(),'Pauline','Viron','pviron@kpmg.fr','collaborator','declared',GETDATE(),''),
(14,NEWID(),'Amaury','Lindé','amaurylinde@kpmg.fr','collaborator','declared',GETDATE(),''),
(15,NEWID(),'Mohammed','Harchaoui','mharchaoui@kpmg.fr','collaborator','declared',GETDATE(),''),
(16,NEWID(),'Arab','Ait Ouarabi','aaitouarabi@kpmg.fr','collaborator','declared',GETDATE(),''),
(17,NEWID(),'Firas','Bey','fbey@kpmg.fr','collaborator','declared',GETDATE(),''),
(18,NEWID(),'Youness','El Gueraoui','yelgueraoui@kpmg.fr','collaborator','declared',GETDATE(),''),
(20,NEWID(),'Clément','Fory','cfory@kpmg.fr','collaborator','declared',GETDATE(),''),
(21,NEWID(),'Suliman','Lescot','slescot@kpmg.fr','collaborator','declared',GETDATE(),''),
(22,NEWID(),'Jerry','Nantenaina','jnantenaina@kpmg.fr','collaborator','declared',GETDATE(),''),
(23,NEWID(),'Bao Trung','Nguyen','baotrungnguyen@kpmg.fr','collaborator','declared',GETDATE(),''),
(24,NEWID(),'Olivier','Peaucelle','opeaucel@kpmg.fr','collaborator','declared',GETDATE(),''),
(25,NEWID(),'Sofiane','Yousfi','syousfi@kpmg.fr','collaborator','declared',GETDATE(),''),
(26,NEWID(),'Thomas','Charrier','tcharrier@kpmg.fr','collaborator','declared',GETDATE(),''),
(27,NEWID(),'Abderazak','Chebbah','achebbah@kpmg.fr','collaborator','declared',GETDATE(),''),
(28,NEWID(),'Coralyse','Haar','chaar@kpmg.fr','collaborator','declared',GETDATE(),''),
(29,NEWID(),'Ouassim','Hayani','ohayani@kpmg.fr','collaborator','declared',GETDATE(),''),
(30,NEWID(),'Thibault','Mestre','tmestre@kpmg.fr','collaborator','declared',GETDATE(),''),
(31,NEWID(),'Mathieu','Parrino','mparrino@kpmg.fr','collaborator','declared',GETDATE(),''),
(32,NEWID(),'Ishola','Adedjouma','iadedjouma@kpmg.fr','collaborator','declared',GETDATE(),''),
(33,NEWID(),'Virgile ','Boussoumah','vboussoumah1@kpmg.fr','collaborator','declared',GETDATE(),''),
(34,NEWID(),'François','Bozza','fbozza@kpmg.fr','collaborator','declared',GETDATE(),''),
(35,NEWID(),'Corinne','Campisciano','ccampisciano@kpmg.fr','collaborator','declared',GETDATE(),''),
(36,NEWID(),'Jimmy','Vidal','Jimmyvidal@kpmg.fr','collaborator','declared',GETDATE(),''),
(37,NEWID(),'Marc','Vincent','marcvincent1@kpmg.fr','collaborator','declared',GETDATE(),''),
(38,NEWID(),'Abd El Jalil','Anane','aanane@kpmg.fr','collaborator','declared',GETDATE(),''),
(39,NEWID(),'Houssem','Dbira','hdbira@kpmg.fr','collaborator','declared',GETDATE(),''),
(40,NEWID(),'Saliou','Dioum','sdioum@kpmg.fr','collaborator','declared',GETDATE(),''),
(41,NEWID(),'Ameur','Elabed','aelabed1@kpmg.fr','collaborator','declared',GETDATE(),''),
(42,NEWID(),'Raphael','Katz','raphaelkatz@kpmg.fr','collaborator','declared',GETDATE(),''),
(43,NEWID(),'Fares','Manadi','fmanadi@kpmg.fr','collaborator','declared',GETDATE(),''),
(44,NEWID(),'Alex','Vigreux','avigreux@kpmg.fr','collaborator','declared',GETDATE(),''),
(45,NEWID(),'Elise','Carenau','ecarenau@kpmg.fr','collaborator','declared',GETDATE(),''),
(46,NEWID(),'Mick','Philippon','mickphilippon@kpmg.fr','collaborator','declared',GETDATE(),''),
(47,NEWID(),'Christophe','Couchut','ccouchut@kpmg.fr','collaborator','declared',GETDATE(),''),
(48,NEWID(),'Clémence','Dewet','cdewet@kpmg.fr','collaborator','declared',GETDATE(),''),
(49,NEWID(),'Marwen','Elleuch','melleuch@kpmg.fr','collaborator','declared',GETDATE(),''),
(50,NEWID(),'Saif Allah','Medini','smedini@kpmg.fr','collaborator','declared',GETDATE(),''),
(51,NEWID(),'Ghislain','Nguepi','gnguepi@kpmg.fr','collaborator','declared',GETDATE(),''),
(52,NEWID(),'Stephane','Nzali','snzali@kpmg.fr','collaborator','declared',GETDATE(),''),
(53,NEWID(),'Clément','Prati','clementprati@kpmg.fr','collaborator','declared',GETDATE(),''),
(54,NEWID(),'Katia','Sana','katiasana@kpmg.fr','collaborator','declared',GETDATE(),''),
(55,NEWID(),'Joan','Fayard','jfayard@kpmg.fr','collaborator','declared',GETDATE(),'')