IF NOT EXISTS (SELECT 1 FROM [account].[THub] WHERE [HubName] = 'Hub Aquitaine Nord')
BEGIN
	INSERT INTO [account].[THub]([HubName]) VALUES
	('Hub Aquitaine Nord'),
	('Hub Languedoc-Roussillon'),
	('Hub Tarn Aveyron'),
	('Hub Toulouse Midi Pyrennées'),
	('Hub Pays Basque Landes'),
	('Hub Atlantique Ouest'),
	('Hub Anjou Maine'),
	('Hub Charente Limousin'),
	('Hub Haute Bretagne'),
	('Hub Nantes Atlantique Vendée'),
	('Hub Bretagne Océan'),
	('Hub La Réunion'),
	('Hub Grand Ouest Parisien'),
	('Hub Centre'),
	('Hub Marne et Oise'),
	('Hub Berry Nivernais'),
	('Hub Paris'),
	('Hub Arc Alpin'),
	('Hub Loire & Drôme Ardèche'),
	('Hub Franche-Comté Bourgogne Nord'),
	('Hub Ain et Lyonnais'),
	('Hub Bourgogne Sud'),
	('Hub Auvergne'),
	('Hub Provence Côte d''Azur'),
	('Hub Normandie Seine Baie de Somme'),
	('Hub Antilles Guyane'),
	('Hub Caen Sud Normandie'),
	('Hub Manche'),
	('Hub Amiens Haute Picardie'),
	('Hub Littoral'),
	('Hub Artois Grand Hainaut'),
	('Hub Estuaire Terre et Mer'),
	('Hub Lille Métropole'),
	('Hub Alsace Nord'),
	('Hub Lorraine Sud'),
	('Hub Alsace Sud'),
	('Hub Champagne-Ardenne'),
	('Hub Lorraine Nord')
END