IF NOT EXISTS (SELECT 1 FROM [account].[Hub] WHERE [HubName] = 'Aquitaine Nord')
BEGIN
	INSERT INTO [account].[Hub]([HubName]) VALUES
	('Aquitaine Nord'),
	('Languedoc-Roussillon'),
	('Tarn Aveyron'),
	('Toulouse Midi Pyrénées'),
	('Pays Basque Landes'),
	('Atlantique Ouest'),
	('Anjou Maine'),
	('Charente Limousin'),
	('Haute Bretagne'),
	('Nantes Atlantique Vendée'),
	('Bretagne Océan'),
	('La Réunion'),
	('Grande Couronne'),
	('Centre'),
	('Amiens Somme Aisne'),
	('Berry Nivernais'),
	('Arc Alpin'),
	('ID&AL'),
	('Franche-Comté Bourgogne Nord'),
	('Ain et Lyonnais'),
	('Bourgogne Sud'),
	('Auvergne'),
	('Provence Côte d''Azur'),
	('Antilles Guyane'),
	('Caen Sud Normandie'),
	('Manche'),
	('Littoral'),
	('Artois Grand Hainaut'),
	('Estuaire Terre et Mer'),
	('Lille Métropole'),
	('Alsace Nord'),
	('Lorraine Sud'),
	('Alsace Sud'),
	('Champagne-Ardenne'),
	('Lorraine Nord'),
	('Paris')
END