IF NOT EXISTS (SELECT * FROM [actor].[Contact] WHERE ContactId = 1)
BEGIN
INSERT into actor.Contact(ContactId, ContactGlobalUniqueId, FirstName, LastName, Email, Type, Status, CreationDate, PersonaName, Office)
VALUES
(1,NEWID(),'Yasser','Arouaoui','yarouaoui@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(2,NEWID(),'Wael','Ben Abdellatif','wbenabdelatif@kpmg.fr','collaborator','declared',GETDATE(),'Assistant(e)','La Défense EQHO'),
(3,NEWID(),'Selim','Ben Slimen','sbenslimen@kpmg.fr','collaborator','declared',GETDATE(),'Partner','La Défense EQHO'),
(4,NEWID(),'Ahmed','Yaiche','ahmedyaiche@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur ESC','La Défense EQHO'),
(5,NEWID(),'Oussema','Ben Amor','obenamor@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur GS','La Défense EQHO'),
(6,NEWID(),'Siwar','Ben Dhafer','sbendhafer@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital GS','La Défense EQHO'),
(7,NEWID(),'Hervé','Chaissac','hchaissac@kpmg.fr','collaborator','declared',GETDATE(),'Middle Office','La Défense EQHO'),
(8,NEWID(),'Naoual','El Farissi','nelfarissi@kpmg.fr','collaborator','declared',GETDATE(),'Support','La Défense EQHO'),
(9,NEWID(),'Kaoutar','Khamliche','kkhamliche@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(10,NEWID(),'Erwan','Munier','emunier@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(11,NEWID(),'Kevin','Pozderec','kpozderec@kpmg.fr','collaborator','declared',GETDATE(),'Assistant(e)','La Défense EQHO'),
(12,NEWID(),'Rayan','Ramanampamonjy','rramanampamonjy@kpmg.fr','collaborator','declared',GETDATE(),'Partner','La Défense EQHO'),
(13,NEWID(),'Pauline','Viron','pviron@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur ESC','La Défense EQHO'),
(14,NEWID(),'Amaury','Lindé','amaurylinde@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur GS','La Défense EQHO'),
(15,NEWID(),'Mohammed','Harchaoui','mharchaoui@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital GS','La Défense EQHO'),
(16,NEWID(),'Arab','Ait Ouarabi','aaitouarabi@kpmg.fr','collaborator','declared',GETDATE(),'Middle Office','La Défense EQHO'),
(17,NEWID(),'Firas','Bey','fbey@kpmg.fr','collaborator','declared',GETDATE(),'Support','La Défense EQHO'),
(18,NEWID(),'Youness','El Gueraoui','yelgueraoui@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital ESC','La Défense EQHO'),
(20,NEWID(),'Clément','Fory','cfory@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(21,NEWID(),'Suliman','Lescot','slescot@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(22,NEWID(),'Jerry','Nantenaina','jnantenaina@kpmg.fr','collaborator','declared',GETDATE(),'Partner','La Défense EQHO'),
(23,NEWID(),'Bao Trung','Nguyen','baotrungnguyen@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur ESC','La Défense EQHO'),
(24,NEWID(),'Olivier','Peaucelle','opeaucel@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur GS','La Défense EQHO'),
(25,NEWID(),'Sofiane','Yousfi','syousfi@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital GS','La Défense EQHO'),
(26,NEWID(),'Thomas','Charrier','tcharrier@kpmg.fr','collaborator','declared',GETDATE(),'Support','La Défense EQHO'),
(27,NEWID(),'Abderazak','Chebbah','achebbah@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital ESC','La Défense EQHO'),
(28,NEWID(),'Coralyse','Haar','chaar@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(29,NEWID(),'Ouassim','Hayani','ohayani@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(30,NEWID(),'Thibault','Mestre','tmestre@kpmg.fr','collaborator','declared',GETDATE(),'Partner','La Défense EQHO'),
(31,NEWID(),'Mathieu','Parrino','mparrino@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur ESC','La Défense EQHO'),
(32,NEWID(),'Ishola','Adedjouma','iadedjouma@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur GS','La Défense EQHO'),
(33,NEWID(),'Virgile ','Boussoumah','vboussoumah1@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital GS','La Défense EQHO'),
(34,NEWID(),'François','Bozza','fbozza@kpmg.fr','collaborator','declared',GETDATE(),'Middle Office','La Défense EQHO'),
(35,NEWID(),'Corinne','Campisciano','ccampisciano@kpmg.fr','collaborator','declared',GETDATE(),'Support','La Défense EQHO'),
(36,NEWID(),'Jimmy','Vidal','Jimmyvidal@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital ESC','La Défense EQHO'),
(37,NEWID(),'Marc','Vincent','marcvincent1@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(38,NEWID(),'Abd El Jalil','Anane','aanane@kpmg.fr','collaborator','declared',GETDATE(),'Assistant(e)','La Défense EQHO'),
(39,NEWID(),'Houssem','Dbira','hdbira@kpmg.fr','collaborator','declared',GETDATE(),'Partner','La Défense EQHO'),
(40,NEWID(),'Saliou','Dioum','sdioum@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur ESC','La Défense EQHO'),
(41,NEWID(),'Ameur','Elabed','aelabed1@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur GS','La Défense EQHO'),
(42,NEWID(),'Raphael','Katz','raphaelkatz@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital GS','La Défense EQHO'),
(43,NEWID(),'Fares','Manadi','fmanadi@kpmg.fr','collaborator','declared',GETDATE(),'Middle Office','La Défense EQHO'),
(44,NEWID(),'Alex','Vigreux','avigreux@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(45,NEWID(),'Elise','Carenau','ecarenau@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital ESC','La Défense EQHO'),
(46,NEWID(),'Mick','Philippon','mickphilippon@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(47,NEWID(),'Christophe','Couchut','ccouchut@kpmg.fr','collaborator','declared',GETDATE(),'Assistant(e)','La Défense EQHO'),
(48,NEWID(),'Clémence','Dewet','cdewet@kpmg.fr','collaborator','declared',GETDATE(),'Partner','La Défense EQHO'),
(49,NEWID(),'Marwen','Elleuch','melleuch@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur ESC','La Défense EQHO'),
(50,NEWID(),'Saif Allah','Medini','smedini@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur GS','La Défense EQHO'),
(51,NEWID(),'Ghislain','Nguepi','gnguepi@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital GS','La Défense EQHO'),
(52,NEWID(),'Stephane','Nzali','snzali@kpmg.fr','collaborator','declared',GETDATE(),'Middle Office','La Défense EQHO'),
(53,NEWID(),'Clément','Prati','clementprati@kpmg.fr','collaborator','declared',GETDATE(),'Admin / Collab Product','La Défense EQHO'),
(54,NEWID(),'Katia','Sana','katiasana@kpmg.fr','collaborator','declared',GETDATE(),'Expert Digital ESC','La Défense EQHO'),
(55,NEWID(),'Joan','Fayard','jfayard@kpmg.fr','collaborator','declared',GETDATE(),'Collaborateur GS','La Défense EQHO')
END