trigger:
  - main

pool:
  vmImage: 'windows-latest'

parameters:
- name: deployToDev
  displayName: 'Déployer sur DEV'
  type: boolean
  default: false
- name: deployToItg
  displayName: 'Déployer sur ITG'
  type: boolean
  default: true
- name: deployToRec
  displayName: 'Déployer sur REC'
  type: boolean
  default: true
- name: deployToPrd
  displayName: 'Déployer sur Prod'
  type: boolean
  default: true

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/delivery/sql.yaml@Pulse
  parameters:
    deployToDev: ${{ parameters.deployToDev }}
    deployToItg: ${{ parameters.deployToItg }}
    deployToRec: ${{ parameters.deployToRec }}
    deployToPrd: ${{ parameters.deployToPrd }}
    srcPath: 01_account/src/Account.Database/Account.Database.sqlproj
    domain: acc
    id: '01'