trigger: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/hotfix/sql.yaml@Pulse
  parameters:
    srcPath: 01_account/src/Account.Database/Account.Database.sqlproj
    domain: acc
    id: '01'