// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pulse.Account.Infrastructure.Entities;

namespace Pulse.Account.Infrastructure.Context;

public partial class AccountContext : DbContext
{
    public AccountContext(DbContextOptions<AccountContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountEntity> AccountEntity { get; set; }

    public virtual DbSet<AddressEntity> AddressEntity { get; set; }

    public virtual DbSet<ContactEntity> ContactEntity { get; set; }

    public virtual DbSet<DelegationEntity> DelegationEntity { get; set; }

    public virtual DbSet<DeploymentEntity> DeploymentEntity { get; set; }

    public virtual DbSet<HubEntity> HubEntity { get; set; }

    public virtual DbSet<LabelEntity> LabelEntity { get; set; }

    public virtual DbSet<NafEntity> NafEntity { get; set; }

    public virtual DbSet<OfficeEntity> OfficeEntity { get; set; }

    public virtual DbSet<PhoneEntity> PhoneEntity { get; set; }

    public virtual DbSet<RoleEntity> RoleEntity { get; set; }

    public virtual DbSet<RoleLabelEntity> RoleLabelEntity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("C_Account_PK");

            entity.ToTable("Account", "account");

            entity.HasIndex(e => e.AccountNumber, "IX_Account_AccountNumber");

            entity.HasIndex(e => e.LegalName, "IX_Account_LegalName");

            entity.HasIndex(e => e.HubId, "IX_Hub_HubId");

            entity.HasIndex(e => e.NafId, "IX_Naf_NafId");

            entity.HasIndex(e => e.OfficeId, "IX_Office_OfficeId");

            entity.HasIndex(e => e.AccountGlobalUniqueId, "UQ_Account_AccountGlobalUniqueId").IsUnique();

            entity.Property(e => e.AccountId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountGlobalUniqueId).HasComment("L''identifiant global de l''entité");
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AccountType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le type de l''entité");
            entity.Property(e => e.AccountingMethod)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le type de comptabilité");
            entity.Property(e => e.ActivityDescription)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Description de l''activité");
            entity.Property(e => e.ActivityType)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Type d''activité");
            entity.Property(e => e.BillingEmail).HasMaxLength(255);
            entity.Property(e => e.BillingFax).HasMaxLength(50);
            entity.Property(e => e.CommercialName)
                .HasMaxLength(255)
                .HasComment("Le  nom commercial de l''entité");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("L''identifiant de l''utilisateur ou du système qui a crée l''entité");
            entity.Property(e => e.CreationDate).HasComment("La date de création");
            entity.Property(e => e.DeliveryEmail).HasMaxLength(255);
            entity.Property(e => e.DeliveryFax).HasMaxLength(50);
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasComment("L''adresse mail de l''entité");
            entity.Property(e => e.FiscalExerciseDuration).HasComment("La durée de l''exercice fiscale");
            entity.Property(e => e.FiscalExerciseStartDate).HasComment("Début Exercice fiscale");
            entity.Property(e => e.FiscalSystem)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le régime fiscale");
            entity.Property(e => e.HubId).HasComment("L''identifiant technique du Hub");
            entity.Property(e => e.IconName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasComment("L''entité est-elle activé");
            entity.Property(e => e.Isin)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le ISIN")
                .HasColumnName("ISIN");
            entity.Property(e => e.LegalForm)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("La forme juridique de l''entité");
            entity.Property(e => e.LegalFormCode)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le code de la forme juridique");
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255)
                .HasComment("La raison social de l''entité");
            entity.Property(e => e.MissionType)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("L''identifiant de l''utilisateur ou du système qui a effectué la dernière modification");
            entity.Property(e => e.NafId).HasComment("L''identifiant technique du code Naf");
            entity.Property(e => e.Sector)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le secteur");
            entity.Property(e => e.SectorCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le code du secteur");
            entity.Property(e => e.Siret)
                .HasMaxLength(14)
                .IsUnicode(false)
                .HasComment("Le Siret");
            entity.Property(e => e.SourceName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StaffSize).HasComment("Le nombre d''employés de l''entité");
            entity.Property(e => e.StaffSizeRange)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("La plage du nombre de salariés ");
            entity.Property(e => e.TaxationSystem)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le Régime d''imposition");
            entity.Property(e => e.Turnover)
                .HasComment("Le chiffre d''affaires")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasComment("La date de la dernière modification");
            entity.Property(e => e.Vat)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("La TVA")
                .HasColumnName("VAT");
            entity.Property(e => e.Vatintra)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Le numéro de TVA intracommunautaire")
                .HasColumnName("VATIntra");
            entity.Property(e => e.Vattype)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Type de TVA")
                .HasColumnName("VATType");

            entity.HasOne(d => d.Hub).WithMany(p => p.AccountEntity)
                .HasForeignKey(d => d.HubId)
                .HasConstraintName("C_Account_Hub_HubId_FK");

            entity.HasOne(d => d.Naf).WithMany(p => p.AccountEntity)
                .HasForeignKey(d => d.NafId)
                .HasConstraintName("C_Account_NafId_FK");

            entity.HasOne(d => d.Office).WithMany(p => p.AccountEntity)
                .HasForeignKey(d => d.OfficeId)
                .HasConstraintName("C_Account_OfficeId_FK");
        });

        modelBuilder.Entity<AddressEntity>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("C_Address_PK");

            entity.ToTable("Address", "account");

            entity.HasIndex(e => e.AccountId, "IDX_Address_AccountId");

            entity.Property(e => e.AddressId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant de l''entité");
            entity.Property(e => e.AddressLine1).HasMaxLength(255);
            entity.Property(e => e.AddressLine2).HasMaxLength(255);
            entity.Property(e => e.AddressLine3).HasMaxLength(255);
            entity.Property(e => e.AddressType)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasComment("Le type d''adresse");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("La ville");
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("Le pays");
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.State)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("Le département");
            entity.Property(e => e.ZipCode)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("Le code postal");

            entity.HasOne(d => d.Account).WithMany(p => p.AddressEntity)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("C_Account_Address_AccountId_FK");
        });

        modelBuilder.Entity<ContactEntity>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("C_Contact_PK");

            entity.ToTable("Contact", "actor");

            entity.HasIndex(e => new { e.Email, e.LastName, e.FirstName, e.IsActive }, "IX_Contact_Email_LastName_FirstName_IsActive");

            entity.HasIndex(e => new { e.Status, e.IsActive }, "IX_Contact_Status_IsActive");

            entity.HasIndex(e => new { e.Type, e.IsActive }, "IX_Contact_Type_IsActive");

            entity.Property(e => e.ContactId)
                .ValueGeneratedNever()
                .HasComment("L''identifiant technique");
            entity.Property(e => e.ContactGlobalUniqueId).HasComment("L''identifiant global du contact");
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("GETDATE()")
                .HasComment("La date de création du contact");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("L''adresse mail du contact");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Le prénom du contact");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.LandPhone)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("Le numéro de téléphone du contact");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Le nom du contact");
            entity.Property(e => e.LastUpdateDate).HasComment("La date de la dernière modification du contact");
            entity.Property(e => e.MobilePhone)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("Le numéro de téléphone portable du contact");
            entity.Property(e => e.Office)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasComment("Le site du contact");
            entity.Property(e => e.PersonaName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le nom du persona");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Le statut de contact");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Le type de contact");
        });

        modelBuilder.Entity<DelegationEntity>(entity =>
        {
            entity.HasKey(e => e.DelegationId).HasName("C_Delegation_PK");

            entity.ToTable("Delegation", "account");

            entity.HasIndex(e => e.DelegateeId, "IDX_Delegation_DelegateeId");

            entity.HasIndex(e => e.DelegatorId, "IDX_Delegation_DelegatorId");

            entity.Property(e => e.DelegationId).HasComment("L''identifiant technique");
            entity.Property(e => e.CreationDate).HasComment("La date de création de la délégation");
            entity.Property(e => e.DelegateeId).HasComment("L''identifiant du délégataire");
            entity.Property(e => e.DelegatorId).HasComment("Le délégateur ");
            entity.Property(e => e.EndDate).HasComment("La date effective de la fin de la délégation");
            entity.Property(e => e.IncludePennylaneAccess).HasComment("Indique si l''accès à Pennylane doit être inclus.");
            entity.Property(e => e.IsAutomaticDelegation).HasComment("Indique s''il s''agit d''une délégation automatique");
            entity.Property(e => e.IsFullDelegation).HasComment("Indique si la délégation concerne l''intégralité du portefeuille ou non");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("La note associé à la délégation");
            entity.Property(e => e.StartDate).HasComment("La date effective du début de la délégation");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("La délégation est-elle active ou non");

            entity.HasOne(d => d.Delegatee).WithMany(p => p.DelegationEntityDelegatee)
                .HasForeignKey(d => d.DelegateeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_DelegationDetail_Contact_FK");

            entity.HasOne(d => d.Delegator).WithMany(p => p.DelegationEntityDelegator)
                .HasForeignKey(d => d.DelegatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Delegation_Contact_DelegatorId_FK");

            entity.HasMany(d => d.Account).WithMany(p => p.Delegation)
                .UsingEntity<Dictionary<string, object>>(
                    "DelegationDetailEntity",
                    r => r.HasOne<AccountEntity>().WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("C_DelegationDetail_Account_FK"),
                    l => l.HasOne<DelegationEntity>().WithMany()
                        .HasForeignKey("DelegationId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("C_DelegationDetail_Delegation_FK"),
                    j =>
                    {
                        j.HasKey("DelegationId", "AccountId").HasName("C_DelegationDetail_PK");
                        j.ToTable("DelegationDetail", "account");
                        j.HasIndex(new[] { "AccountId" }, "IDX_DelegationDetail_AccountId");
                        j.IndexerProperty<int>("DelegationId").HasComment("L''identifiant technique de la délégation");
                        j.IndexerProperty<int>("AccountId").HasComment("L''identifiant technique de l''entité");
                    });
        });

        modelBuilder.Entity<DeploymentEntity>(entity =>
        {
            entity.HasKey(e => e.DeploymentId)
                .HasName("C_Deployment_PK")
                .IsClustered(false);

            entity.ToTable("Deployment", "account");

            entity.HasIndex(e => e.AccountId, "IXC_Deployment_AccountId").IsClustered();

            entity.HasIndex(e => e.DeploymentId, "IX_Deployment_DeploymentId");

            entity.HasIndex(e => e.Status, "IX_Deployment_Status");

            entity.HasIndex(e => e.AccountId, "UQ_AccountId").IsUnique();

            entity.Property(e => e.DeploymentId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant technique de l''entité");
            entity.Property(e => e.DeploymentDate).HasComment("La date à laquelle le déploiement a eu lieu ");
            entity.Property(e => e.Status).HasComment("Le statut du déploiement");

            entity.HasOne(d => d.Account).WithOne(p => p.DeploymentEntity)
                .HasForeignKey<DeploymentEntity>(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Account_Deployment_FK");
        });

        modelBuilder.Entity<HubEntity>(entity =>
        {
            entity.HasKey(e => e.HubId).HasName("C_Hub_PK");

            entity.ToTable("Hub", "account");

            entity.Property(e => e.HubId).HasComment("L''identifiant technique");
            entity.Property(e => e.HubName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le nom du Hub");
        });

        modelBuilder.Entity<LabelEntity>(entity =>
        {
            entity.HasKey(e => e.LabelId);

            entity.ToTable("Label", "account");

            entity.HasIndex(e => e.Code, "UNIQUE_CODE").IsUnique();

            entity.Property(e => e.Business)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CollaboratorLabel)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CustomerLabel)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Description).HasMaxLength(2000);
            entity.Property(e => e.IsVisible).HasDefaultValue(true);
        });

        modelBuilder.Entity<NafEntity>(entity =>
        {
            entity.HasKey(e => e.NafId).HasName("C_Naf_PK");

            entity.ToTable("Naf", "account");

            entity.Property(e => e.NafId).HasComment("L''identifiant technique");
            entity.Property(e => e.NafCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("Le code Naf de l''entité");
            entity.Property(e => e.NafLabel)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<OfficeEntity>(entity =>
        {
            entity.HasKey(e => e.OfficeId).HasName("C_Office_PK");

            entity.ToTable("Office", "account");

            entity.HasIndex(e => e.AddressId, "IX_Address_AddressId");

            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Address).WithMany(p => p.OfficeEntity)
                .HasForeignKey(d => d.AddressId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Account_Office_AddressId_FK");
        });

        modelBuilder.Entity<PhoneEntity>(entity =>
        {
            entity.HasKey(e => e.PhoneId).HasName("C_Phone_PK");

            entity.ToTable("Phone", "account");

            entity.HasIndex(e => e.AccountId, "IDX_Phone_AccountId");

            entity.Property(e => e.PhoneId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant techique de l''entité");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le numéro de téléphone");
            entity.Property(e => e.Type)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasComment("Le type du numéro de téléphone");

            entity.HasOne(d => d.Account).WithMany(p => p.PhoneEntity)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Account_Phone_AccountId_FK");
        });

        modelBuilder.Entity<RoleEntity>(entity =>
        {
            entity.HasKey(e => new { e.ContactId, e.AccountId }).HasName("C_Role_PK");

            entity.ToTable("Role", "account");

            entity.HasIndex(e => new { e.AccountId, e.ContactId }, "C_Role_AccountId_ContactId").IsUnique();

            entity.HasIndex(e => e.IsCustomerRelation, "IX_Role_IsCustomerRelation");

            entity.HasIndex(e => e.IsFavorite, "IX_Role_IsFavorite");

            entity.HasIndex(e => e.IsSignatory, "IX_Role_IsSignatory");

            entity.Property(e => e.ContactId).HasComment("L''identifiant technique du contact");
            entity.Property(e => e.AccountId).HasComment("L''identifiant technique de l''entité");
            entity.Property(e => e.IsDelegation).HasComment("Indique, dans les cas où c''est possible, si le role est lié à une délégation");
            entity.Property(e => e.IsFavorite).HasComment("Le rôle est-il considéré comme un favori ou mis en avant comme tel");
            entity.Property(e => e.IsSignatory).HasComment("Le signataire");

            entity.HasOne(d => d.Account).WithMany(p => p.RoleEntity)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Account_Role_FK");

            entity.HasOne(d => d.Contact).WithMany(p => p.RoleEntity)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Account_Contact_FK");
        });

        modelBuilder.Entity<RoleLabelEntity>(entity =>
        {
            entity.HasKey(e => new { e.AccountId, e.ContactId, e.LabelId });

            entity.ToTable("RoleLabel", "account");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("GETDATE()")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Account).WithMany(p => p.RoleLabelEntity)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Contact).WithMany(p => p.RoleLabelEntityContact)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.RoleLabelEntityCreatedByNavigation)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Label).WithMany(p => p.RoleLabelEntity)
                .HasForeignKey(d => d.LabelId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}