// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pulse.Account.Infrastructure.Entities;

namespace Pulse.Account.Infrastructure.Context;

public partial class AccountContext : DbContext
{
    public AccountContext(DbContextOptions<AccountContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TAccount> TAccount { get; set; }

    public virtual DbSet<TAddress> TAddress { get; set; }

    public virtual DbSet<TContact> TContact { get; set; }

    public virtual DbSet<TDelegation> TDelegation { get; set; }

    public virtual DbSet<TDeploymentPlanning> TDeploymentPlanning { get; set; }

    public virtual DbSet<THub> THub { get; set; }

    public virtual DbSet<TNaf> TNaf { get; set; }

    public virtual DbSet<TPhone> TPhone { get; set; }

    public virtual DbSet<TRole> TRole { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TAccount>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("C_TAccount_PK");

            entity.ToTable("TAccount", "account");

            entity.HasIndex(e => e.AccountGlobalUniqueId, "IDX_TAccount_AccountGlobalUniqueId");

            entity.HasIndex(e => e.HubId, "IDX_THub_HubId");

            entity.HasIndex(e => e.NafId, "IDX_TNaf_NafId");

            entity.HasIndex(e => e.AccountGlobalUniqueId, "UQ_TAccount_AccountGlobalUniqueId").IsUnique();

            entity.HasIndex(e => e.AccountGlobalUniqueId, "UQ_TPhone_PhoneId").IsUnique();

            entity.Property(e => e.AccountId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountGlobalUniqueId).HasComment("L''identifiant global de l''entité");
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.AccountType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le type de l''entité");
            entity.Property(e => e.AccountingMethod)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le type de comptabilité");
            entity.Property(e => e.ActivityDescription)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Description de l''activité");
            entity.Property(e => e.ActivityType)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Type d''activité");
            entity.Property(e => e.CommercialName)
                .HasMaxLength(255)
                .HasComment("Le  nom commercial de l''entité");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("L''identifiant de l''utilisateur ou du système qui a crée l''entité");
            entity.Property(e => e.CreationDate).HasComment("La date de création");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("L''adresse mail de l''entité");
            entity.Property(e => e.FiscalExerciseDuration).HasComment("La durée de l''exercice fiscale");
            entity.Property(e => e.FiscalExerciseStartDate).HasComment("Début Exercice fiscale");
            entity.Property(e => e.FiscalSystem)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le régime fiscale");
            entity.Property(e => e.HubId).HasComment("L''identifiant technique du Hub");
            entity.Property(e => e.ISIN)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le ISIN");
            entity.Property(e => e.IconName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasComment("L''entité est-elle activé");
            entity.Property(e => e.LegalForm)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("La forme juridique de l''entité");
            entity.Property(e => e.LegalFormCode)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le code de la forme juridique");
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255)
                .HasComment("La raison social de l''entité");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("L''identifiant de l''utilisateur ou du système qui a effectué la dernière modification");
            entity.Property(e => e.NafId).HasComment("L''identifiant technique du code Naf");
            entity.Property(e => e.Sector)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le secteur");
            entity.Property(e => e.SectorCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le code du secteur");
            entity.Property(e => e.Siret)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le Siret");
            entity.Property(e => e.SourceAccountNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("La source de création de l''entité");
            entity.Property(e => e.StaffSize).HasComment("Le nombre d''employés de l''entité");
            entity.Property(e => e.StaffSizeRange)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("La plage du nombre de salariés ");
            entity.Property(e => e.TaxationSystem)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le Régime d''imposition");
            entity.Property(e => e.Turnover)
                .HasComment("Le chiffre d''affaires")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedDate).HasComment("La date de la dernière modification");
            entity.Property(e => e.VAT)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("La TVA");
            entity.Property(e => e.VATIntra)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Le numéro de TVA intracommunautaire");
            entity.Property(e => e.VATType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Type de TVA");

            entity.HasOne(d => d.Hub).WithMany(p => p.TAccount)
                .HasForeignKey(d => d.HubId)
                .HasConstraintName("C_TAccount_THub_HubId_FK");

            entity.HasOne(d => d.Naf).WithMany(p => p.TAccount)
                .HasForeignKey(d => d.NafId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TAccount_TNafId_FK");
        });

        modelBuilder.Entity<TAddress>(entity =>
        {
            entity.HasKey(e => e.AddressId).HasName("C_TAddress_PK");

            entity.ToTable("TAddress", "account");

            entity.HasIndex(e => e.AccountId, "IDX_TAddress_AccountId");

            entity.Property(e => e.AddressId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant de l''entité");
            entity.Property(e => e.AddressLine1).HasMaxLength(255);
            entity.Property(e => e.AddressLine2).HasMaxLength(255);
            entity.Property(e => e.AddressLine3).HasMaxLength(255);
            entity.Property(e => e.AddressType)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasComment("Le type d''adresse");
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("La ville");
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le pays");
            entity.Property(e => e.State)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le département");
            entity.Property(e => e.ZipCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Le code postal");

            entity.HasOne(d => d.Account).WithMany(p => p.TAddress)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TAccount_TAddress_AccountId_FK");
        });

        modelBuilder.Entity<TContact>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("C_TContact_PK");

            entity.ToTable("TContact", "actor");

            entity.HasIndex(e => e.ContactGlobalUniqueId, "IDX_TContact_ContactGlobalUniqueId");

            entity.Property(e => e.ContactId).HasComment("L''identifiant technique");
            entity.Property(e => e.ContactEmail)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("l''adresse mail du contact");
            entity.Property(e => e.ContactGlobalUniqueId).HasComment("L''identifiant global du contact");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le prénom du contact");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Le nom du contact");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Le type de contact");
        });

        modelBuilder.Entity<TDelegation>(entity =>
        {
            entity.HasKey(e => e.DelegationId).HasName("C_TDelegation_PK");

            entity.ToTable("TDelegation", "account");

            entity.HasIndex(e => e.AccountId, "IDX_TDelegation_AccountId");

            entity.HasIndex(e => e.DelegateeId, "IDX_TDelegation_DelegateeId");

            entity.HasIndex(e => e.DelegatorId, "IDX_TDelegation_DelegatorId");

            entity.Property(e => e.DelegationId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant technique de l''entité");
            entity.Property(e => e.CreationDate).HasComment("La date de création de la délégation");
            entity.Property(e => e.DelegateeId).HasComment("Le délégataire");
            entity.Property(e => e.DelegatorId).HasComment("Le délégateur ");
            entity.Property(e => e.EndDate).HasComment("La date effective de la fin de la délégation");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasComment("La note associé à la délégation");
            entity.Property(e => e.StartDate).HasComment("La date effective du début de la délégation");
            entity.Property(e => e.Status).HasComment("La délégation est-elle active ou non");

            entity.HasOne(d => d.Account).WithMany(p => p.TDelegation)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TDelegation_TAccount_FK");

            entity.HasOne(d => d.Delegatee).WithMany(p => p.TDelegationDelegatee)
                .HasForeignKey(d => d.DelegateeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TDelegation_TContact_DelegateeId_FK");

            entity.HasOne(d => d.Delegator).WithMany(p => p.TDelegationDelegator)
                .HasForeignKey(d => d.DelegatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TDelegation_TContact_DelegatorId_FK");
        });

        modelBuilder.Entity<TDeploymentPlanning>(entity =>
        {
            entity.HasKey(e => e.DeploymentId).HasName("C_TDeploymentPlanning_PK");

            entity.ToTable("TDeploymentPlanning", "account");

            entity.HasIndex(e => e.AccountId, "IDX_TDeploymentPlanning_AccountId");

            entity.Property(e => e.DeploymentId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant technique de l''entité");
            entity.Property(e => e.DeploymentDate).HasComment("La date à laquelle le déploiement a eu lieu ");
            entity.Property(e => e.Status).HasComment("Le statut du déploiement");

            entity.HasOne(d => d.Account).WithMany(p => p.TDeploymentPlanning)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TAccount_TDeployment_FK");
        });

        modelBuilder.Entity<THub>(entity =>
        {
            entity.HasKey(e => e.HubId).HasName("C_THub_PK");

            entity.ToTable("THub", "account");

            entity.Property(e => e.HubId).HasComment("L''identifiant technique");
            entity.Property(e => e.HubName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasComment("Le nom du Hub");
        });

        modelBuilder.Entity<TNaf>(entity =>
        {
            entity.HasKey(e => e.NafId).HasName("C_TNaf_PK");

            entity.ToTable("TNaf", "account");

            entity.Property(e => e.NafId).HasComment("L''identifiant technique");
            entity.Property(e => e.NafCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("Le code Naf de l''entité");
            entity.Property(e => e.NafLabel)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TPhone>(entity =>
        {
            entity.HasKey(e => e.PhoneId).HasName("C_TPhone_PK");

            entity.ToTable("TPhone", "account");

            entity.HasIndex(e => e.AccountId, "IDX_TPhone_AccountId");

            entity.Property(e => e.PhoneId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant techique de l''entité");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasComment("Le numéro de téléphone");
            entity.Property(e => e.Type)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasComment("Le type du numéro de téléphone");

            entity.HasOne(d => d.Account).WithMany(p => p.TPhone)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TAccount_TPhone_AccountId_FK");
        });

        modelBuilder.Entity<TRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("C_TRole_PK");

            entity.ToTable("TRole", "account");

            entity.HasIndex(e => new { e.AccountId, e.ContactId }, "C_TRole_AccountId_ContactId").IsUnique();

            entity.HasIndex(e => e.AccountId, "IDX_TRole_AccountId");

            entity.HasIndex(e => e.ContactId, "IDX_TRole_ContactId");

            entity.Property(e => e.RoleId).HasComment("L''identifiant technique");
            entity.Property(e => e.AccountId).HasComment("L''identifiant technique de l''entité");
            entity.Property(e => e.ContactId).HasComment("L''identifiant technique du contact");
            entity.Property(e => e.IsFavorite).HasComment("Le rôle est-il considéré comme un favori ou mis en avant comme tel");
            entity.Property(e => e.IsSignatory).HasComment("Le signataire");

            entity.HasOne(d => d.Account).WithMany(p => p.TRole)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TAccount_TRole_FK");

            entity.HasOne(d => d.Contact).WithMany(p => p.TRole)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_TAccount_TContact_FK");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}