// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Kpmg.Offer.Infrastructure.Entities;

namespace Kpmg.Offer.Infrastructure.Context
{
    public partial class OfferContext : DbContext
    {
        public OfferContext(DbContextOptions<OfferContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TOffer> TOffer { get; set; }
        public virtual DbSet<TProduct> TProduct { get; set; }
        public virtual DbSet<TProductConfiguration> TProductConfiguration { get; set; }
        public virtual DbSet<TProvider> TProvider { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            if (modelBuilder != null)
            {
                modelBuilder.Entity<TOffer>(entity =>
                {
                    entity.HasKey(e => e.OfferId)
                        .HasName("C_TOffer_PK");

                    entity.ToTable("TOffer", "sch_offr");

                    entity.Property(e => e.OfferId).HasComment("ID technique");

                    entity.Property(e => e.ApprovalRequired).HasComment("Indique si une validation est nécessaire ou non");

                    entity.Property(e => e.GlobalOfferId).HasComment("ID technique utilisé dans la base Constellation");

                    entity.Property(e => e.IntranetLink)
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasComment("Lien vers le lien intranet");

                    entity.Property(e => e.LogoName)
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasComment("Logo de l'offre");

                    entity.Property(e => e.OfferDescription)
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasComment("Description de l'offre");

                    entity.Property(e => e.OfferLabel)
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasComment("Libellé de l'offre");

                    entity.Property(e => e.OfferName)
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasComment("Nom de l'offre");

                    entity.Property(e => e.OfferPrice)
                        .HasColumnType("decimal(12, 2)")
                        .HasComment("Prix de l'offre");

                    entity.Property(e => e.OfferPriceType)
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    entity.Property(e => e.OffersBookLink)
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasComment("Lien vers le book des offres");

                    entity.Property(e => e.Tags)
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasComment("Liste de tags");
                });

                modelBuilder.Entity<TProduct>(entity =>
                {
                    entity.HasKey(e => e.ProductId)
                        .HasName("C_TProduct_PK");

                    entity.ToTable("TProduct", "sch_offr");

                    entity.Property(e => e.ProductId).HasComment("ID technique");

                    entity.Property(e => e.Enabled)
                        .IsRequired()
                        .HasDefaultValueSql("1")
                        .HasComment("Indique si le service est disponible ou non");

                    entity.Property(e => e.ProductBusiness)
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasComment("Comptabilité, gestion sociale, juridique, transverse");

                    entity.Property(e => e.ProductDescription)
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasComment("Description du service");

                    entity.Property(e => e.ProductLabel)
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasComment("Libellé service");

                    entity.Property(e => e.ProductName)
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasComment("Nom du service");

                    entity.Property(e => e.ProviderId).HasComment("Acteur externe, Pulse, équipe BI...");

                    entity.Property(e => e.PublicProductDescription)
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasComment("Description public du service");

                    entity.Property(e => e.PublicProductLabel)
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasComment("Libellé public du service");

                    entity.Property(e => e.PublicProductName)
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasComment("Nom public du service");

                    entity.HasOne(d => d.TProvider)
                        .WithMany(p => p.TProduct)
                        .HasForeignKey(d => d.ProviderId)
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TProduct_TProvider");
                });

                modelBuilder.Entity<TProductConfiguration>(entity =>
                {
                    entity.HasKey(e => e.ProductConfigurationId)
                        .HasName("PK_sch_offr.TProductConfiguration");

                    entity.ToTable("TProductConfiguration", "sch_offr");

                    entity.HasIndex(e => e.OfferId, "IDX_ProductConfiguration_Offer");

                    entity.HasIndex(e => e.ProductId, "IDX_ProductConfiguration_Product");

                    entity.Property(e => e.ProductConfigurationId).HasComment("ID technique");

                    entity.Property(e => e.Date).HasComment("Date");

                    entity.Property(e => e.Enabled).HasComment("Si le service est activé ou non");

                    entity.Property(e => e.GlobalProductConfigurationId).HasComment("ID technique utilisé dans la base Constellation");

                    entity.Property(e => e.IsOptionnal).HasComment("Si le service est obligatoire ou optionnel dans l'offre associée");

                    entity.Property(e => e.OfferId).HasComment("ID de l'offre associée");

                    entity.Property(e => e.Price)
                        .HasColumnType("decimal(12, 2)")
                        .HasComment("Prix du service (s'il est optionnel)");

                    entity.Property(e => e.PriceType)
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasComment("Le type du prix du produit");

                    entity.Property(e => e.ProductId).HasComment("ID du service associé");

                    entity.HasOne(d => d.TOffer)
                        .WithMany(p => p.TProductConfiguration)
                        .HasForeignKey(d => d.OfferId)
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TProductConfiguration_TOffer");

                    entity.HasOne(d => d.TProduct)
                        .WithMany(p => p.TProductConfiguration)
                        .HasForeignKey(d => d.ProductId)
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TProductConfiguration_TProduct");
                });

                modelBuilder.Entity<TProvider>(entity =>
                {
                    entity.HasKey(e => e.ProviderId)
                        .HasName("C_TProvider_PK");

                    entity.ToTable("TProvider", "sch_offr");

                    entity.Property(e => e.ProviderId).HasComment("ID technique");

                    entity.Property(e => e.LogoName)
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasComment("Logo du provider");

                    entity.Property(e => e.ProviderCategory)
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasComment("Pulse, interne KPMG ou externe");

                    entity.Property(e => e.ProviderEditor)
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasComment("Nom de l'éditeur de la prestation");

                    entity.Property(e => e.ProviderName)
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasComment("Nom de la prestation commerciale");
                });

                OnModelCreatingPartial(modelBuilder);
            }
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
