INSERT into actor.Contact(ContactId, ContactGlobalUniqueId, FirstName, LastName, Email, Type, Status, CreationDate, PersonaName,Office)
VALUES
(74, NEWID(),'Erwan','Duval','erwanduval@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(75, NEWID(),'Jeremie','Georges','jeremiegeorges@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(76, NEWID(),'Quentin','Meyer','quentinmeyer@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(77, NEWID(),'Celine','Lopes','celinelopes@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(78, NEWID(),'Clémence','Fribaut','cfribault@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(79, NEWID(),'Florian','Davy','fdavy@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(80, NEWID(),'Julien','Gauthie','jgauthie@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(81, NEWID(),'Arnaud','Szczachor','aszczachor@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(82, NEWID(),'Lucie','Guedon','lguedon@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(83, NEWID(),'Pauline','Thepaut','pthepaut@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(84, NEWID(),'Julien','Da Costa Lopes','jdacostalopes@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(85, NEWID(),'Clément','Briquet','cbriquet@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(86, NEWID(),'Geofrroy','Bodin','gbodin@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(87, NEWID(),'Solene','Munich','smunich@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(88, NEWID(),'Aurore','Maier','amaier@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(89, NEWID(),'Matthieu','Rimlinger','mrimlinger@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(90, NEWID(),'Mathieu','Chancerel','mchancerel@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(91, NEWID(),'Melissa','Gregoire','melissagregoire@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(92, NEWID(),'Julien','Filhastre','jfilhastre@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(93, NEWID(),'Camille','Risse','crisse@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(94, NEWID(),'Lea','Balzano','lbalzano@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(95, NEWID(),'Yoan','Jeanrot','yjeanrot@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(96, NEWID(),'Sébastien','Chartaud','schartaud@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(97, NEWID(),'Robin','Toth','robintoth@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(98, NEWID(),'Nathalie','Feignon','nfeignon@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(99, NEWID(),'Cédric','Chatel','cedricchatel@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(100, NEWID(),'Mathieu','Oliveira Dos Reis','moliveiradosreis@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(101, NEWID(),'Caroline','Mathieu','carolinemathieu@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(102, NEWID(),'Remi','Defond','rdefond@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(103, NEWID(),'Christophe','Cardoso','christophecardoso@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(104, NEWID(),'Francois','Thomas','francoisthomas@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(105, NEWID(),'Florent','Cailler','fcaillier@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(106, NEWID(),'Maxime','Fauvel-Schlusselhuber','mfauvel-schlusselhub@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(107, NEWID(),'Mathilde','Zaccardi ','mzaccardi@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(108, NEWID(),'Romaric','Belliard','rbelliard@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(109, NEWID(),'Quentin','Lagrave','qlagrave@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(110, NEWID(),'Charles','Bechet','cbechet@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(111, NEWID(),'Ugo','Dejob','udejob@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(112, NEWID(),'Louis','Poittevin','lpoittevin@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(113, NEWID(),'Sarah','Arcioni','sarcioni@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(114, NEWID(),'Yassine','Madani','ymadani@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(115, NEWID(),'Pierre-Louis','Baranes','pbaranes@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(116, NEWID(),'Celia','Cala','ccala@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(117, NEWID(),'Thomas','Kerneis','tkerneis@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(118, NEWID(),'Sabrina','Brun','sabrinabrun@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(119, NEWID(),'Cloe','Ferral','cferal@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(120, NEWID(),'Laurence','Biard-Olivry','lbiard-olivry@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(121, NEWID(),'Thomas','Saxton','lsaxton@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(122, NEWID(),'Hugo','Grunfelder','tgrunfelder@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(123, NEWID(),'Hugo','Brechenmacher','hbrechenmacher@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(124, NEWID(),'Olivier','Tabaux','otabaux@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(125, NEWID(),'Jessie','Coquerel','jcoquerel@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(126, NEWID(),'Charlotte','Andries','candries@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(127, NEWID(),'Jan','Bleschke','jbleschke@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(128, NEWID(),'Alexis','Roger','alexisroger@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(129, NEWID(),'Florian','Lamoot','flamoot@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(130, NEWID(),'Luc ','Koudjowa','lkoudjowa@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(131, NEWID(),'Candice','Brunel','cbrunel@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(132, NEWID(),'Gaelle','Robin','grobin@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(133, NEWID(),'Ylann','Joly','yjoly@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(134, NEWID(),'Maxime','Willez','mwillez@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(135, NEWID(),'Anne','Vivenot','annevivenot@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(136, NEWID(),'Baptiste','Rousee','brousee@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(137, NEWID(),'Roger','Louis','rlouis@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(138, NEWID(),'Cindy','Douilly','cdouilly@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(139, NEWID(),'Amel','Lamrous ','alamrous@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(140, NEWID(),'Romane','Debard','rdebard@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(141, NEWID(),'Arnaud','Bernstein','arnaudbernstein@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(142, NEWID(),'Emilie','Gaida','egaida@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(143, NEWID(),'Coline','Muller','colinemuller@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(144, NEWID(),'Maud','Morel','maudmorel@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(145, NEWID(),'Jean-Roger','Pem','jrpem@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(146, NEWID(),'Stephanie','Depinoy','sdepinoy@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(147, NEWID(),'Cyril','Courbi','ccourbi@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(148, NEWID(),'Baptiste','Fumeron-Lecompte','bfumeron-lecomte@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(149, NEWID(),'Kevin','Cambien','kcambien@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(150, NEWID(),'Amelie','Martin','ameliemartin@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(151, NEWID(),'Romain','Le Plaire','rleplaire@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(152, NEWID(),'Cendrine','Poletto','cpoletto@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(153, NEWID(),'Vincent','Aristizabal','varistizabal@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(154, NEWID(),'Pierre ','Barcelo','pbarcelo@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(155, NEWID(),'Denise','Kalaner','dkalaner@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(156, NEWID(),'Jean-Christophe','Beme','jbeme@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(157, NEWID(),'Florence','Bronkhorst','fbronkhorst@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(158, NEWID(),'Amandine','Deleurence','adeleurence@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(159, NEWID(),'Herve','Holo','hholo@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(160, NEWID(),'Mathieu','Gentot','mgentot@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(161, NEWID(),'Céline','OLIVER','celineoliver@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(162, NEWID(),'Pauline','MOREL','ppomes@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(163, NEWID(),'Nicolas','RAYMOND ','nraymond@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(164, NEWID(),'Vincent','LE DARZ','vledarz@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(165, NEWID(),'Paola','FRANCOIS','paolafrancois@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(166, NEWID(),'Gwenaëlle','ESLAN','gchauvin@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(167, NEWID(),'Julien','LE LAY','julienlelay@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(168, NEWID(),'Ratiba','MAALOUL','rmaaloul@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(169, NEWID(),'Nicolas','APAYA-GADABAYA','nicolasapaya@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(170, NEWID(),'Karine','BEAL','kbeal@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(171, NEWID(),'Natacha','BARROCHET','nbarochet@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(172, NEWID(),'Jamila','Belmehdi','jbelmehdi@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(173, NEWID(),'Mathilde','Toualiri','mtoualiri@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(174, NEWID(),'Damien','GEIST','dgeist@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(175, NEWID(),'Julie','Guibert','jguibert@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(176, NEWID(),'Angelina','Belhaire','abelhaire@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(177, NEWID(),'Laëtitia','Collet','lcollet@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(178, NEWID(),'Sarah','Padieu','spadieu@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC'),
(179, NEWID(),'Coralie','Voisin','cvoisin@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(180, NEWID(),'Flavie','Delorme','fdelorme@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital GS'),
(181, NEWID(),'Delphine','Pousse','dpousse@kpmg.fr','Collaborator','Declared',GETDATE(),'Expert digital ESC')